import { useEffect, useState } from 'react';
import { NavLink } from 'react-router-dom';
import UserSidebar from '../components/UserSidebar.jsx';

const sections = [['/admin', 'Resumen'], ['/admin/equipo', 'Equipo'], ['/admin/registros', 'Registros'], ['/admin/correcciones', 'Correcciones'], ['/admin/informes', 'Informes'], ['/admin/configuracion', 'Configuración']];
const days = [['mon', 'Lun'], ['tue', 'Mar'], ['wed', 'Mié'], ['thu', 'Jue'], ['fri', 'Vie'], ['sat', 'Sáb'], ['sun', 'Dom']];
const defaults = { organization: { legalName: '', taxId: '', address: '', contact: '' }, workday: { weeklyHours: 40, days: ['mon', 'tue', 'wed', 'thu', 'fri'], maxDailyHours: 12, allowOvernight: true, allowMultipleSegments: true, breakRule: 'configured', minBreaks: 1, maxBreaks: 2, minBreakMinutes: 15, maxBreakMinutes: 120, breakAfterHours: 6, breakCountsAsWork: false }, approvals: { mode: 'manual', autoApproveDelaySeconds: 5, autoApproveModifications: false }, retention: { years: 4, backupFrequency: 'Diaria', reportTimezone: 'Europe/Madrid' } };
const merge = value => ({ ...defaults, ...value, organization: { ...defaults.organization, ...(value?.organization || {}) }, workday: { ...defaults.workday, ...(value?.workday || {}), days: value?.workday?.days || defaults.workday.days }, approvals: { ...defaults.approvals, ...(value?.approvals || {}) }, retention: { ...defaults.retention, ...(value?.retention || {}) } });

export default function AdminConfig() {
  const [tenantId, setTenantId] = useState(''); const [tenant, setTenant] = useState(null); const [form, setForm] = useState(defaults); const [message, setMessage] = useState('Cargando configuración…'); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { const me = await fetch('/api/v1/me').then(r => r.ok ? r.json() : null); if (!me?.tenant?.id) throw new Error('No hay una organización disponible.'); setTenantId(me.tenant.id); setTenant(me.tenant); const response = await fetch(`/api/v1/tenants/${encodeURIComponent(me.tenant.id)}/settings`); const data = response.ok ? await response.json() : {}; setForm(merge(data.settings)); setMessage(''); })().catch(error => setMessage(error.message)); }, []);
  const update = (group, key, value) => setForm(current => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const toggleDay = day => update('workday', 'days', form.workday.days.includes(day) ? form.workday.days.filter(item => item !== day) : [...form.workday.days, day]);
  async function save(event) { event.preventDefault(); if (!form.workday.days.length) { setMessage('Selecciona al menos un día laborable.'); return; } if (form.workday.breakRule === 'configured' && form.workday.minBreakMinutes > form.workday.maxBreakMinutes) { setMessage('La duración mínima de pausa no puede superar la máxima.'); return; } setSaving(true); setMessage(''); const response = await fetch(`/api/v1/tenants/${encodeURIComponent(tenantId)}/settings`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); setSaving(false); setMessage(response.ok ? 'Configuración guardada.' : (data.message || 'No se pudo guardar la configuración.')); if (response.ok) setForm(merge(data.settings)); }
  return <div className="workspace"><UserSidebar userLinks={false} showPersonal={false}><nav className="admin-side-nav" aria-label="Administración">{sections.map(([path, label]) => <NavLink key={path} to={path} end={path === '/admin'} className={({ isActive }) => isActive ? 'selected' : undefined}>{label}</NavLink>)}</nav></UserSidebar><div className="main"><div className="eyebrow">Administración · Organización</div><h1>Configuración</h1><p>Define cómo funciona {tenant?.name || 'tu organización'} y cómo se revisan sus cambios.</p>{message && <p className="team-message" role="status">{message}</p>}<form className="settings-grid" onSubmit={save}>
    <section className="card"><h3>Datos de la organización</h3><div className="settings-fields"><label>Razón social<input value={form.organization.legalName} onChange={e => update('organization', 'legalName', e.target.value)} placeholder={tenant?.name || 'Nombre legal'} /></label><label>CIF/NIF<input value={form.organization.taxId} onChange={e => update('organization', 'taxId', e.target.value)} /></label><label>Dirección<input value={form.organization.address} onChange={e => update('organization', 'address', e.target.value)} /></label><label>Contacto administrativo<input value={form.organization.contact} onChange={e => update('organization', 'contact', e.target.value)} /></label></div></section>
    <section className="card"><h3>Reglas de jornada</h3><div className="settings-block"><span className="settings-label">Días laborables</span><div className="day-picker">{days.map(([value, label]) => <label key={value} className={form.workday.days.includes(value) ? 'day-option selected' : 'day-option'}><input type="checkbox" checked={form.workday.days.includes(value)} onChange={() => toggleDay(value)} />{label}</label>)}</div><div className="settings-presets"><button type="button" onClick={() => update('workday', 'days', days.slice(0, 5).map(([value]) => value))}>Lunes a viernes</button><button type="button" onClick={() => update('workday', 'days', days.slice(0, 6).map(([value]) => value))}>Lunes a sábado</button><button type="button" onClick={() => update('workday', 'days', days.map(([value]) => value))}>Todos los días</button></div></div><div className="settings-fields"><label>Horas semanales<input type="number" min="1" max="80" value={form.workday.weeklyHours} onChange={e => update('workday', 'weeklyHours', Number(e.target.value))} /></label><label>Máximo diario (horas)<input type="number" min="1" max="24" value={form.workday.maxDailyHours} onChange={e => update('workday', 'maxDailyHours', Number(e.target.value))} /></label></div><div className="settings-checks"><label><input type="checkbox" checked={form.workday.allowOvernight} onChange={e => update('workday', 'allowOvernight', e.target.checked)} /> Permitir jornadas que crucen medianoche</label><label><input type="checkbox" checked={form.workday.allowMultipleSegments} onChange={e => update('workday', 'allowMultipleSegments', e.target.checked)} /> Permitir varios tramos en un día</label></div></section>
    <section className="card"><h3>Pausas</h3><div className="settings-fields"><label>Regla<select value={form.workday.breakRule} onChange={e => update('workday', 'breakRule', e.target.value)}><option value="none">Sin regla específica</option><option value="configured">Configurar pausas</option></select></label><label>Exigir pausa después de (horas)<input type="number" min="0" max="24" step="0.5" value={form.workday.breakAfterHours} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'breakAfterHours', Number(e.target.value))} /></label><label>Pausas mínimas<input type="number" min="0" max="20" value={form.workday.minBreaks} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'minBreaks', Number(e.target.value))} /></label><label>Pausas máximas<input type="number" min="0" max="20" value={form.workday.maxBreaks} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'maxBreaks', Number(e.target.value))} /></label><label>Duración mínima (minutos)<input type="number" min="0" max="1440" value={form.workday.minBreakMinutes} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'minBreakMinutes', Number(e.target.value))} /></label><label>Duración máxima (minutos)<input type="number" min="0" max="1440" value={form.workday.maxBreakMinutes} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'maxBreakMinutes', Number(e.target.value))} /></label></div><div className="settings-checks"><label><input type="checkbox" checked={form.workday.breakCountsAsWork} disabled={form.workday.breakRule === 'none'} onChange={e => update('workday', 'breakCountsAsWork', e.target.checked)} /> La pausa cuenta como tiempo trabajado</label></div></section>
    <section className="card"><h3>Aprobación de cambios</h3><div className="settings-fields"><label>Flujo<select value={form.approvals.mode} onChange={e => update('approvals', 'mode', e.target.value)}><option value="manual">Revisión manual</option><option value="auto_demo">Autoaprobar en modo demo</option><option value="mixed">Modificaciones simples automáticas</option></select></label><label>Espera demo (segundos)<input type="number" min="1" max="60" value={form.approvals.autoApproveDelaySeconds} onChange={e => update('approvals', 'autoApproveDelaySeconds', Number(e.target.value))} /></label></div><div className="settings-checks"><label><input type="checkbox" checked={form.approvals.autoApproveModifications} onChange={e => update('approvals', 'autoApproveModifications', e.target.checked)} /> Permitir autoaprobación de modificaciones simples</label></div><p className="muted">Las eliminaciones y jornadas completas siguen requiriendo revisión manual.</p></section>
    <section className="card"><h3>Auditoría, backups e informes</h3><div className="settings-fields"><label>Conservación (años)<input type="number" min="1" max="20" value={form.retention.years} onChange={e => update('retention', 'years', Number(e.target.value))} /></label><label>Frecuencia de backup<select value={form.retention.backupFrequency} onChange={e => update('retention', 'backupFrequency', e.target.value)}><option>Diaria</option><option>Semanal</option></select></label><label>Zona horaria de informes<select value={form.retention.reportTimezone} onChange={e => update('retention', 'reportTimezone', e.target.value)}><option>Europe/Madrid</option><option>UTC</option></select></label></div><p className="muted">Los cambios de configuración quedan registrados en auditoría.</p></section>
    <div className="settings-summary"><span className="eyebrow">Resumen activo</span><p>{form.workday.days.length === 7 ? 'Todos los días' : form.workday.days.map(day => days.find(item => item[0] === day)?.[1]).join(', ')} · {form.workday.weeklyHours} h semanales · {form.workday.breakRule === 'none' ? 'sin regla de pausas' : `${form.workday.minBreaks}–${form.workday.maxBreaks} pausas de ${form.workday.minBreakMinutes}–${form.workday.maxBreakMinutes} min después de ${form.workday.breakAfterHours} h`}</p></div><div className="settings-actions"><button className="cta" type="submit" disabled={saving || !tenantId}>{saving ? 'Guardando…' : 'Guardar configuración'}</button></div>
  </form></div></div>;
}
