import { useEffect, useState } from 'react';
import UserSidebar from '../components/UserSidebar.jsx';

export default function Profile() {
  const [profile, setProfile] = useState({ user: { name: 'Laia Soler', email: 'laia@plegat.local', id: 'demo-user' }, tenant: { name: 'Demo Textil Mediterránea' } });
  const [demo, setDemo] = useState(true); const [form, setForm] = useState({ name: '', email: '' }); const [password, setPassword] = useState({ current: '', next: '', confirm: '' }); const [avatar, setAvatar] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch('/api/v1/me').then(r => r.ok ? r.json() : null).then(data => { if (data) { setProfile(data); setForm({ name: data.user.name || '', email: data.user.email || '' }); setDemo(false); } else setForm({ name: 'Laia Soler', email: 'laia@plegat.local' }); }).catch(() => setForm({ name: 'Laia Soler', email: 'laia@plegat.local' })); const saved = localStorage.getItem('plegat_demo_avatar'); if (saved) setAvatar(saved); }, []);
  function saveProfile(event) { event.preventDefault(); if (demo) { const next = { ...profile, user: { ...profile.user, name: form.name, email: form.email } }; setProfile(next); localStorage.setItem('plegat_demo_profile', JSON.stringify(next)); setMessage('Perfil guardado en la demo.'); return; } fetch('/api/v1/me/profile', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }).then(r => r.json()).then(data => { if (data.user) { setProfile(current => ({ ...current, user: data.user })); setMessage('Perfil actualizado.'); } else setMessage(data.message || 'No se pudo actualizar el perfil.'); }).catch(() => setMessage('No se pudo conectar con el servidor.')); }
  function savePassword(event) { event.preventDefault(); if (password.next.length < 12 || password.next !== password.confirm) { setMessage('La nueva contraseña debe tener 12 caracteres y coincidir.'); return; } fetch('/api/v1/me/password', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ currentPassword: password.current, newPassword: password.next }) }).then(r => r.json()).then(data => { setMessage(data.message || (data.ok ? 'Contraseña actualizada.' : 'No se pudo cambiar la contraseña.')); if (data.ok) setPassword({ current: '', next: '', confirm: '' }); }).catch(() => setMessage('No se pudo conectar con el servidor.')); }
  function photo(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { setAvatar(reader.result); localStorage.setItem('plegat_demo_avatar', reader.result); }; reader.readAsDataURL(file); }
  return <div className="workspace"><UserSidebar /><div className="main"><div className="eyebrow">Cuenta personal</div><h1>Mi perfil</h1><p>Gestiona tus datos y tu acceso a Plegat.</p><div className="profile-grid"><section className="card profile-card"><div className="profile-avatar-large">{avatar ? <img src={avatar} alt="" /> : profile.user.name?.slice(0, 1).toUpperCase()}</div><span className="muted">{profile.tenant?.name || 'Demo Textil Mediterránea'}</span><small>ID de usuario · {profile.user.id}</small></section><section className="card profile-form-card"><h3>Datos personales</h3><form className="auth-form" onSubmit={saveProfile}><label>Nombre<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /></label><label>Email<input type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /></label><button className="cta" type="submit">Guardar cambios</button></form></section><section className="card profile-form-card"><h3>Cambiar contraseña</h3><form className="auth-form" onSubmit={savePassword}><label>Contraseña actual<input type="password" value={password.current} onChange={e => setPassword({ ...password, current: e.target.value })} required /></label><label>Nueva contraseña<input type="password" minLength="12" value={password.next} onChange={e => setPassword({ ...password, next: e.target.value })} required /></label><label>Repetir contraseña<input type="password" minLength="12" value={password.confirm} onChange={e => setPassword({ ...password, confirm: e.target.value })} required /></label><button className="cta secondary" type="submit">Cambiar contraseña</button></form></section></div><p role="status">{message}</p></div></div>;
}
