import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import UserSidebar from '../components/UserSidebar.jsx';

const read = key => { try { return JSON.parse(localStorage.getItem(key) || 'null'); } catch { return null; } };
const id = prefix => `${prefix}-${crypto.randomUUID()}`;
const localValue = value => value ? new Date(value).toISOString().slice(0, 16) : '';
const labels = { clock_in: 'Entrada', break_start: 'Inicio de pausa', break_end: 'Fin de pausa', clock_out: 'Salida' };
function toSegments(events) { const ordered = [...events].sort((a,b) => new Date(a.occurredAt)-new Date(b.occurredAt)); const result=[]; let segment=null; let pause=null; for (const event of ordered) { if (event.type==='clock_in') { if(segment) result.push(segment); segment={id:id('segment'), originalId:event.id, start:localValue(event.occurredAt), end:'', pauses:[]}; } else if(event.type==='break_start' && segment) pause={id:id('pause'), originalId:event.id, start:localValue(event.occurredAt), end:''}; else if(event.type==='break_end' && segment && pause) { pause.end=localValue(event.occurredAt); segment.pauses.push(pause); pause=null; } else if(event.type==='clock_out' && segment) { segment.end=localValue(event.occurredAt); result.push(segment); segment=null; pause=null; } } if(segment) result.push(segment); return result; }
function flatten(segments) { return segments.flatMap(segment => [{id:segment.originalId || id('draft'), type:'clock_in', occurredAt:segment.start}, ...segment.pauses.flatMap(pause => [{id:pause.originalId || id('draft'), type:'break_start', occurredAt:pause.start}, {id:id('draft'), type:'break_end', occurredAt:pause.end}]), {id:id('draft'), type:'clock_out', occurredAt:segment.end}]); }
export default function WorkdayEditor() {
  const [authenticated, setAuthenticated] = useState(false);
  const [remoteEvents, setRemoteEvents] = useState(null);
  const [remoteRequests, setRemoteRequests] = useState(null);
  useEffect(() => { fetch('/api/v1/me').then(response => { setAuthenticated(response.ok); if (response.ok) return Promise.all([fetch('/api/v1/me/attendance').then(result => result.ok ? result.json() : null), fetch('/api/v1/me/corrections').then(result => result.ok ? result.json() : null)]); return null; }).then(data => { if (data) { if (data[0]?.events) setRemoteEvents(data[0].events); if (data[1]?.requests) setRemoteRequests(data[1].requests); } }).catch(() => setAuthenticated(false)); }, []);
  const { date }=useParams(); const navigate=useNavigate(); const stored=useMemo(()=>read('plegat_demo_attendance')?.events||[],[]); const localRequests=useMemo(()=>read('plegat_correction_requests')||[],[]); const requests=remoteRequests || localRequests; const remoteDayEvents=useMemo(()=>date&&date!=='nueva'?(remoteEvents||[]).filter(e=>e.occurredAt.slice(0,10)===date):[],[date,remoteEvents]); const initial=useMemo(()=>date&&date!=='nueva'?stored.filter(e=>e.occurredAt.slice(0,10)===date):[],[date,stored]); const proposal=useMemo(()=>date&&date!=='nueva'?[...requests].filter(r=>(r.status==='pending'||r.status==='approved')&&(r.kind==='create_workday'||r.kind==='edit_workday')&&(r.originalTime||r.original_time)?.slice(0,10)===date).sort((a,b)=>new Date(b.createdAt||b.created_at)-new Date(a.createdAt||a.created_at))[0]:null,[date,requests]); const proposalEvents=proposal?.proposedEvents||proposal?.proposal?.proposedEvents||proposal?.proposal?.events||[]; const source=proposalEvents.length?proposalEvents:remoteDayEvents.length?remoteDayEvents:initial; const creating=!date||date==='nueva'||source.length===0; const day=date&&date!=='nueva'?date:new Date().toISOString().slice(0,10); const [segments,setSegments]=useState(()=>toSegments(source)); const [reason,setReason]=useState(''); const [message,setMessage]=useState('');
  useEffect(() => { if (source.length) setSegments(toSegments(source)); }, [remoteEvents, remoteRequests, date, proposal]);
  const update=(sid,field,value)=>setSegments(s=>s.map(x=>x.id===sid?{...x,[field]:value}:x)); const updatePause=(sid,pid,field,value)=>setSegments(s=>s.map(x=>x.id===sid?{...x,pauses:x.pauses.map(p=>p.id===pid?{...p,[field]:value}:p)}:x));
  const addSegment=()=>setSegments(s=>[...s,{id:id('segment'),start:`${day}T09:00`,end:`${day}T17:00`,pauses:[]}]); const addPause=sid=>setSegments(s=>s.map(x=>x.id===sid?{...x,pauses:[...x.pauses,{id:id('pause'),start:`${day}T13:00`,end:`${day}T13:15` }]}:x));
  const duration=segments.reduce((sum,s)=>sum+Math.max(0,+new Date(s.end)-+new Date(s.start)-s.pauses.reduce((p,x)=>p+Math.max(0,+new Date(x.end)-+new Date(x.start)),0)),0); const pauseCount=segments.reduce((sum,s)=>sum+s.pauses.length,0);
  async function submit(e){e.preventDefault(); const proposed=flatten(segments).sort((a,b)=>new Date(a.occurredAt)-new Date(b.occurredAt)); const invalid=!segments.length||segments.some(s=>!s.start||!s.end||new Date(s.end)<=new Date(s.start)||s.pauses.some(p=>!p.start||!p.end||new Date(p.start)<new Date(s.start)||new Date(p.end)>new Date(s.end)||new Date(p.end)<=new Date(p.start))); const overlap=proposed.some((x,i)=>i&&new Date(x.occurredAt)<=new Date(proposed[i-1].occurredAt)); if(invalid||overlap){setMessage('Revisa los tramos: cada jornada debe tener entrada, salida y pausas válidas, sin solapamientos.');return;} if(!reason.trim()){setMessage('Indica el motivo para mantener la trazabilidad.');return;} if(authenticated){ const response=await fetch('/api/v1/me/corrections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:creating?'create_workday':'edit_workday',originalTime:`${day}T00:00:00.000Z`,reason:reason.trim(),proposal:{proposedEvents:proposed}})}); if(!response.ok){setMessage('No se pudo guardar la propuesta en el servidor.');return;} navigate('/historial'); return; } const requests=read('plegat_correction_requests')||[]; const request={id:crypto.randomUUID(),kind:creating?'create_workday':'edit_workday',eventType:'workday',originalTime:`${day}T00:00:00.000Z`,originalEvents:initial,proposedEvents:proposed,reason:reason.trim(),status:'pending',createdAt:new Date().toISOString()}; localStorage.setItem('plegat_correction_requests',JSON.stringify([...requests,request])); window.setTimeout(()=>{const current=read('plegat_correction_requests')||[];localStorage.setItem('plegat_correction_requests',JSON.stringify(current.map(x=>x.id===request.id?{...x,status:'approved',approvedAt:new Date().toISOString(),approvedBy:'demo-auto'}:x)));},5000); navigate('/historial');}
  return <div className="workspace"><UserSidebar/><div className="main"><div className="eyebrow">{creating?'Nueva jornada':'Edición auditable'}</div><h1>{creating?'Crear jornada':'Editar jornada'}</h1><p>{new Date(`${day}T12:00:00`).toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><form className="card workday-editor" onSubmit={submit}><div className="editor-summary"><div><span className="muted">Estado</span><strong>{proposal?.status==='approved'?'Propuesta aprobada':proposal?.status==='pending'?'Propuesta pendiente':segments.length?'Jornada cerrada':'Sin actividad'}</strong></div><div><span className="muted">Tiempo efectivo</span><strong>{Math.floor(duration/3600000)} h {Math.round(duration/60000)%60} min</strong></div><div><span className="muted">Pausas</span><strong>{pauseCount}</strong></div></div><div className="row editor-title"><h3>Tramos de jornada</h3><button type="button" onClick={addSegment}>+ Añadir tramo</button></div>{!segments.length&&<p className="empty-state">No hay jornada registrada. Añade un tramo para empezar.</p>}{segments.map((s,i)=><section className="editor-segment" key={s.id}><div className="row"><h3>Tramo {i+1}</h3><button type="button" className="quiet-action" onClick={()=>setSegments(v=>v.filter(x=>x.id!==s.id))}>Eliminar tramo</button></div><div className="editor-event"><label>Entrada<input type="datetime-local" value={s.start} onChange={e=>update(s.id,'start',e.target.value)} required/></label><label>Salida<input type="datetime-local" value={s.end} onChange={e=>update(s.id,'end',e.target.value)} required/></label></div>{s.pauses.map((p,j)=><div className="editor-pause" key={p.id}><div className="row"><strong>Pausa {j+1}</strong><button type="button" className="quiet-action" onClick={()=>update(s.id,'pauses',s.pauses.filter(x=>x.id!==p.id))}>Eliminar pausa</button></div><div className="editor-event"><label>Inicio<input type="datetime-local" value={p.start} onChange={e=>updatePause(s.id,p.id,'start',e.target.value)} required/></label><label>Fin<input type="datetime-local" value={p.end} onChange={e=>updatePause(s.id,p.id,'end',e.target.value)} required/></label></div></div>)}<button type="button" className="create-day-link" onClick={()=>addPause(s.id)}>+ Añadir pausa</button></section>)}<label className="editor-reason">Motivo de {creating?'creación':'modificación'}<textarea value={reason} onChange={e=>setReason(e.target.value)} rows="4" required placeholder="Explica qué ocurrió y por qué debe corregirse…"/></label><div className="actions"><button type="button" onClick={()=>navigate('/historial')}>Cancelar</button><button className="cta" type="submit">Guardar propuesta de jornada</button></div><small role="status">{message||'Los fichajes originales se conservarán para auditoría.'}</small></form></div></div>;


}
